#!/usr/bin/env node
/**
 * scan.js - 扫描 skills 目录并生成 INDEX.md 和 _redirects
 *
 * 使用方法：node scripts/scan.js
 *
 * 配置：
 *   所有域名配置在 scripts/config.js 中
 *   可以通过环境变量覆盖默认配置：
 *   BASE_URL=https://custom.com/files node scripts/scan.js
 *   DOMAIN=https://example.com node scripts/scan.js
 */

const fs = require('fs');
const path = require('path');
const config = require('./config');

const SKILLS_DIR = path.join(__dirname, '..', 'skills');
const OUTPUT_INDEX = path.join(SKILLS_DIR, 'INDEX.md');
const OUTPUT_REDIRECTS = path.join(__dirname, '..', '_redirects');
const AGENTS_TEMPLATE = path.join(__dirname, '..', 'AGENTS.md.template');
const OUTPUT_AGENTS = path.join(__dirname, '..', 'AGENTS.md');

/**
 * 获取 skill 的完整 URL
 */
function getSkillUrl(skillPath) {
  return config.getSkillUrl(skillPath);
}

/**
 * 解析 YAML frontmatter
 */
function parseFrontmatter(content) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return {};

  const yaml = match[1];
  const result = {};

  const lines = yaml.split(/\r?\n/);
  for (const line of lines) {
    const kv = line.split(':');
    if (kv.length >= 2) {
      const key = kv[0].trim();
      const value = kv.slice(1).join(':').trim().replace(/['"]/g, '');
      result[key] = value;
    }
  }

  return result;
}

/**
 * 递归获取目录下所有文件
 */
function getAllFiles(dirPath, basePath = '') {
  const files = [];

  if (!fs.existsSync(dirPath)) return files;

  const entries = fs.readdirSync(dirPath, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dirPath, entry.name);
    const relativePath = path.join(basePath, entry.name);

    if (entry.isDirectory()) {
      files.push(...getAllFiles(fullPath, relativePath));
    } else {
      files.push(relativePath);
    }
  }

  return files;
}

/**
 * 扫描 skills 目录
 */
function scanSkills() {
  const skills = [];

  if (!fs.existsSync(SKILLS_DIR)) {
    console.error('Skills directory not found:', SKILLS_DIR);
    return skills;
  }

  const entries = fs.readdirSync(SKILLS_DIR, { withFileTypes: true });

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;

    const skillDir = path.join(SKILLS_DIR, entry.name);
    const skillMd = path.join(skillDir, 'SKILL.md');

    if (!fs.existsSync(skillMd)) continue;

    const content = fs.readFileSync(skillMd, 'utf-8');
    const frontmatter = parseFrontmatter(content);

    const allFiles = getAllFiles(skillDir);

    skills.push({
      name: frontmatter.name || entry.name,
      description: frontmatter.description || '',
      path: entry.name,
      files: allFiles
    });
  }

  return skills;
}

/**
 * 生成 INDEX.md 内容
 */
function generateIndex(skills) {
  const headerPath = path.join(SKILLS_DIR, 'INDEX_HEADER.md');
  let md = fs.existsSync(headerPath)
    ? fs.readFileSync(headerPath, 'utf-8')
    : `# Skill Catalog\n\n<!-- Auto-generated by scan.js -->\n\n## Skills\n\n`;

  for (const skill of skills) {
    md += `### ${skill.name}\n`;
    md += `- **Description**: ${skill.description}\n`;
    md += `- **Raw**: ${getSkillUrl(skill.path)}\n\n`;
  }

  return md;
}

/**
 * 生成 _redirects 内容
 */
function generateRedirects(skills) {
  let redirects = `# Auto-generated by scan.js - DO NOT EDIT MANUALLY\n`;
  redirects += `# Skill 目录重定向到 SKILL.md\n\n`;
  redirects += `/ /INDEX.md 200\n\n`;

  for (const skill of skills) {
    redirects += `/${skill.path} /${skill.path}/SKILL.md 200\n`;
    redirects += `/${skill.path}/ /${skill.path}/SKILL.md 200\n`;
  }

  return redirects;
}

/**
 * 生成 AGENTS.md 内容
 */
function generateAgents() {
  if (!fs.existsSync(AGENTS_TEMPLATE)) {
    console.log('AGENTS.md.template not found, skipping AGENTS.md generation');
    return;
  }

  let template = fs.readFileSync(AGENTS_TEMPLATE, 'utf-8');
  template = template.replace(/\{\{BASE_URL\}\}/g, config.baseUrl);
  fs.writeFileSync(OUTPUT_AGENTS, template);
  console.log('Generated AGENTS.md');
}

/**
 * 主函数
 */
function main() {
  console.log('Scanning skills directory...');
  console.log(`Using base URL: ${config.baseUrl}`);

  const skills = scanSkills();

  if (skills.length === 0) {
    console.log('No skills found. Create at least one skill with SKILL.md');
    fs.writeFileSync(OUTPUT_INDEX, '# Skill Catalog\n\n_No skills found. Add a skill by creating a directory with SKILL.md._\n');
    return;
  }

  const indexContent = generateIndex(skills);
  fs.writeFileSync(OUTPUT_INDEX, indexContent);
  console.log('Generated INDEX.md');

  const redirectsContent = generateRedirects(skills);
  fs.writeFileSync(path.join(__dirname, '..', '_redirects'), redirectsContent);
  console.log('Generated _redirects');

  generateAgents();

  console.log(`Found ${skills.length} skill(s): ${skills.map(s => s.name).join(', ')}`);
}

main();
