#!/usr/bin/env node
/**
 * scan.js - 扫描 skills 目录并生成 INDEX.md 和 _redirects
 *
 * 使用方法：node scripts/scan.js
 */

const fs = require('fs');
const path = require('path');

const SKILLS_DIR = path.join(__dirname, '..', 'skills');
const OUTPUT_INDEX = path.join(SKILLS_DIR, 'INDEX.md');
const OUTPUT_REDIRECTS = path.join(__dirname, '..', '_redirects');

/**
 * 解析 YAML frontmatter
 */
function parseFrontmatter(content) {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return {};

  const yaml = match[1];
  const result = {};

  // 简单解析 YAML
  const lines = yaml.split('\n');
  for (const line of lines) {
    const kv = line.split(':');
    if (kv.length >= 2) {
      const key = kv[0].trim();
      const value = kv.slice(1).join(':').trim().replace(/['"]/g, '');
      result[key] = value;
    }
  }

  return result;
}

/**
 * 递归获取目录下所有文件
 */
function getAllFiles(dirPath, basePath = '') {
  const files = [];

  if (!fs.existsSync(dirPath)) return files;

  const entries = fs.readdirSync(dirPath, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dirPath, entry.name);
    const relativePath = path.join(basePath, entry.name);

    if (entry.isDirectory()) {
      files.push(...getAllFiles(fullPath, relativePath));
    } else {
      files.push(relativePath);
    }
  }

  return files;
}

/**
 * 扫描 skills 目录
 */
function scanSkills() {
  const skills = [];

  if (!fs.existsSync(SKILLS_DIR)) {
    console.error('Skills directory not found:', SKILLS_DIR);
    return skills;
  }

  const entries = fs.readdirSync(SKILLS_DIR, { withFileTypes: true });

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;

    const skillDir = path.join(SKILLS_DIR, entry.name);
    const skillMd = path.join(skillDir, 'SKILL.md');

    if (!fs.existsSync(skillMd)) continue;

    // 读取 frontmatter
    const content = fs.readFileSync(skillMd, 'utf-8');
    const frontmatter = parseFrontmatter(content);

    // 获取所有文件
    const allFiles = getAllFiles(skillDir);

    skills.push({
      name: frontmatter.name || entry.name,
      description: frontmatter.description || '',
      path: entry.name,
      files: allFiles
    });
  }

  return skills;
}

/**
 * 生成 INDEX.md 内容
 */
function generateIndex(skills) {
  let md = `# Skill Catalog\n\n`;
  md += `<!-- Auto-generated by scan.js -->\n\n`;
  md += `## Skills\n\n`;

  for (const skill of skills) {
    md += `### ${skill.name}\n`;
    md += `- **Description**: ${skill.description}\n`;
    md += `- **Path**: /${skill.path}/SKILL.md\n\n`;
  }

  return md;
}

/**
 * 生成 _redirects 内容
 */
function generateRedirects(skills) {
  let redirects = `# Auto-generated by scan.js - DO NOT EDIT MANUALLY\n`;
  redirects += `# Skill 目录重定向到 SKILL.md\n\n`;

  // 根路径重定向到 INDEX.md
  redirects += `/ /INDEX.md 200\n\n`;

  for (const skill of skills) {
    // 无尾部斜杠
    redirects += `/${skill.path} /${skill.path}/SKILL.md 200\n`;
    // 有尾部斜杠
    redirects += `/${skill.path}/ /${skill.path}/SKILL.md 200\n`;
  }

  return redirects;
}

/**
 * 主函数
 */
function main() {
  console.log('Scanning skills directory...');

  const skills = scanSkills();

  if (skills.length === 0) {
    console.log('No skills found. Create at least one skill with SKILL.md');
    // 生成空的 INDEX.md
    fs.writeFileSync(OUTPUT_INDEX, '# Skill Catalog\n\n_No skills found. Add a skill by creating a directory with SKILL.md._\n');
    return;
  }

  // 生成 INDEX.md
  const indexContent = generateIndex(skills);
  fs.writeFileSync(OUTPUT_INDEX, indexContent);
  console.log('Generated INDEX.md');

  // 生成 _redirects
  const redirectsContent = generateRedirects(skills);
  fs.writeFileSync(path.join(__dirname, '..', '_redirects'), redirectsContent);
  console.log('Generated _redirects');

  console.log(`Found ${skills.length} skill(s): ${skills.map(s => s.name).join(', ')}`);
}

main();
